// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9Eoo28yHJOsMLDcv4IAOr0mHf3rsgBg',
    appId: '1:795317250647:android:6c2718e8d421c610489112',
    messagingSenderId: '795317250647',
    projectId: 'gita-ai-5cdf6',
    storageBucket: 'gita-ai-5cdf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANIW2XvAlQcbz1Hpj4hCrPjOravgueL00',
    appId: '1:795317250647:ios:f2fc0e055403e764489112',
    messagingSenderId: '795317250647',
    projectId: 'gita-ai-5cdf6',
    storageBucket: 'gita-ai-5cdf6.appspot.com',
    iosBundleId: 'com.example.geminiChatBot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqJXuBUoVO5dpxwbI1DmtndXF9ST-xSA',
    appId: '1:795317250647:web:0955ff1ba8406f9e489112',
    messagingSenderId: '795317250647',
    projectId: 'gita-ai-5cdf6',
    authDomain: 'gita-ai-5cdf6.firebaseapp.com',
    storageBucket: 'gita-ai-5cdf6.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANIW2XvAlQcbz1Hpj4hCrPjOravgueL00',
    appId: '1:795317250647:ios:f2fc0e055403e764489112',
    messagingSenderId: '795317250647',
    projectId: 'gita-ai-5cdf6',
    storageBucket: 'gita-ai-5cdf6.appspot.com',
    iosBundleId: 'com.example.geminiChatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrqJXuBUoVO5dpxwbI1DmtndXF9ST-xSA',
    appId: '1:795317250647:web:df81bf9eab1abd9e489112',
    messagingSenderId: '795317250647',
    projectId: 'gita-ai-5cdf6',
    authDomain: 'gita-ai-5cdf6.firebaseapp.com',
    storageBucket: 'gita-ai-5cdf6.appspot.com',
  );

}